from src.price_monitor.model.line_item_option_code import LineItemOptionCode

models_data = {
    "result": {
        "activeModels": {
            "A220W4": {
                "modelBuildPage": None,
                "model": {
                    "lineExists": False,
                },
            },
            "C43W4": {
                "modelBuildPage": "/en/vehicles/build/c-class/sedan/c43w4/lines",
                "model": {
                    "lineExists": True,
                },
            },
            "C300A": {
                "modelBuildPage": "/en/vehicles/build/c-class/cabriolet/c300a",
                "model": {
                    "lineExists": False,
                },
            },
        }
    }
}

option_code_list = [
    LineItemOptionCode(
        code="040",
        description="Black",
        type="PAINT",
        included=True,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="149",
        description="Polar White",
        type="PAINT",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="197",
        description="Obsidian Black metallic",
        type="PAINT",
        included=False,
        net_list_price=750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="831",
        description="Graphite Grey metallic",
        type="PAINT",
        included=False,
        net_list_price=750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="859",
        description="Mojave Silver metallic",
        type="PAINT",
        included=False,
        net_list_price=750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="890",
        description="Lunar Blue metallic",
        type="PAINT",
        included=False,
        net_list_price=750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="922",
        description="Cirrus Silver metallic",
        type="PAINT",
        included=False,
        net_list_price=750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="992",
        description="Selenite Grey metallic",
        type="PAINT",
        included=False,
        net_list_price=750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="970",
        description="Starling Blue metallic",
        type="PAINT",
        included=False,
        net_list_price=750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="996",
        description="MANUFAKTUR Cardinal Red metallic",
        type="PAINT",
        included=False,
        net_list_price=1750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="799",
        description="MANUFAKTUR Diamond White metallic",
        type="PAINT",
        included=False,
        net_list_price=1750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="740",
        description="Black",
        type="SOFT_TOP",
        included=True,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="744",
        description="Dark Blue",
        type="SOFT_TOP",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="742",
        description="Red",
        type="SOFT_TOP",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="22R",
        description="18-inch split 5-spoke",
        type="WHEELS",
        included=True,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="RSJ",
        description="18-inch AMG 5-spoke",
        type="WHEELS",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="RSK",
        description="18-inch AMG 5-spoke w/black accents",
        type="WHEELS",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="788",
        description="19-inch AMG multispoke",
        type="WHEELS",
        included=False,
        net_list_price=600.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="665",
        description="19-inch AMG multispoke w/black accents",
        type="WHEELS",
        included=False,
        net_list_price=600.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="604",
        description="19-inch AMG twin 5-spoke w/black accents",
        type="WHEELS",
        included=False,
        net_list_price=600.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="DG3",
        description="AMG Line",
        type="PACKAGES",
        included=False,
        net_list_price=1750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="DC1",
        description="AMG Line w/Night Package",
        type="PACKAGES",
        included=False,
        net_list_price=2150.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="D03",
        description="Illuminated Star",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=450.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="D08",
        description="Chrome door handle inserts",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=100.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040009001127",
        description="AMG hub cap, in centre lock design",
        type="ACCESSORIES",
        included=False,
        net_list_price=37.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040009001190",
        description="AMG hub cap, in centre lock design",
        type="ACCESSORIES",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040009002232",
        description="AMG hub cap, in centre lock design",
        type="ACCESSORIES",
        included=False,
        net_list_price=43.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040009003594",
        description="AMG hub cap, in centre lock design",
        type="ACCESSORIES",
        included=False,
        net_list_price=42.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040009009283",
        description="AMG hub cap, in centre lock design",
        type="ACCESSORIES",
        included=False,
        net_list_price=44.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040009009790",
        description="AMG hub cap, in centre lock design",
        type="ACCESSORIES",
        included=False,
        net_list_price=42.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0004003100",
        description="AMG hub cap, with AMG emblem, set of 4",
        type="ACCESSORIES",
        included=False,
        net_list_price=268.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2057604200",
        description="Door handle recesses, small, 2-piece",
        type="ACCESSORIES",
        included=False,
        net_list_price=85.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2058175701",
        description="Illuminated Mercedes star, trim part",
        type="ACCESSORIES",
        included=False,
        net_list_price=262.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B66030017",
        description="AMG hub cap, with AMG emblem, set of 4",
        type="ACCESSORIES",
        included=False,
        net_list_price=332.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B66472004",
        description="AMG valve caps, with Affalterbach badge",
        type="ACCESSORIES",
        included=False,
        net_list_price=45.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B66472005",
        description="AMG valve caps, with Affalterbach badge",
        type="ACCESSORIES",
        included=False,
        net_list_price=54.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0004001600",
        description="AMG hub cap, with AMG emblem",
        type="ACCESSORIES",
        included=False,
        net_list_price=72.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="101",
        description="Black MB-Tex",
        type="UPHOLSTERY",
        included=True,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="105",
        description="Silk Beige/Black MB-Tex",
        type="UPHOLSTERY",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="124",
        description="Saddle Brown/Black MB-Tex",
        type="UPHOLSTERY",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="201",
        description="Black leather",
        type="UPHOLSTERY",
        included=False,
        net_list_price=1620.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="224",
        description="Saddle Brown/Black leather",
        type="UPHOLSTERY",
        included=False,
        net_list_price=1620.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="225",
        description="Porcelain/Black leather",
        type="UPHOLSTERY",
        included=False,
        net_list_price=1620.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="227",
        description="Cranberry Red/Black leather",
        type="UPHOLSTERY",
        included=False,
        net_list_price=1620.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="H07",
        description="Dark Brown Linden wood",
        type="TRIM",
        included=True,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="737",
        description="Natural Grain Black Ash wood and aluminum",
        type="TRIM",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="H31",
        description="Natural Grain Grey Oak wood",
        type="TRIM",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="H33",
        description="Natural Grain Walnut wood and aluminum",
        type="TRIM",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="242",
        description="3-position memory for passenger seat",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=350.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="401",
        description="Ventilated front seats",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=450.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="U09",
        description="Topstitched MB-Tex upper dash and door trim",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=350.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="443",
        description="Heated steering wheel",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=250.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="D43",
        description="All-season front and rear floor mats, black rubber",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=170.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0002900500",
        description="Sports pedals in stainless steel, automatic models, with rubber studs",
        type="ACCESSORIES",
        included=False,
        net_list_price=181.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0007660800",
        description="AMG door pin, round",
        type="ACCESSORIES",
        included=False,
        net_list_price=47.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A1778108103",
        description="Ashtray",
        type="ACCESSORIES",
        included=False,
        net_list_price=66.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="DA5",
        description="Multimedia Package",
        type="PACKAGES",
        included=False,
        net_list_price=1250.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="463",
        description="Head-Up Display",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=1100.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="897",
        description="Inductive wireless charging and NFC pairing",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=200.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0009820021",
        description="Rectifier",
        type="ACCESSORIES",
        included=False,
        net_list_price=74.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2038400020",
        description="Shopping crate, collapsible",
        type="ACCESSORIES",
        included=False,
        net_list_price=15.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2058608900",
        description="Luggage net, floor of load compartment",
        type="ACCESSORIES",
        included=False,
        net_list_price=84.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2138204402",
        description="Media Interface consumer cable, micro USB",
        type="ACCESSORIES",
        included=False,
        net_list_price=26.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2138204502",
        description="Media Interface consumer cable, Lightning",
        type="ACCESSORIES",
        included=False,
        net_list_price=48.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2238209903",
        description="Bluetooth® headphones",
        type="ACCESSORIES",
        included=False,
        net_list_price=354.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2228208700",
        description="Media Interface consumer cable, Lightning",
        type="ACCESSORIES",
        included=False,
        net_list_price=96.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2228208800",
        description="Media Interface consumer cable kit",
        type="ACCESSORIES",
        included=False,
        net_list_price=94.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2228200300",
        description="Media Interface consumer cable, Lightning, for iPhone® holder",
        type="ACCESSORIES",
        included=False,
        net_list_price=88.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2228204315",
        description="Media Interface consumer cable, iPod®",
        type="ACCESSORIES",
        included=False,
        net_list_price=93.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2228204415",
        description="Media Interface consumer cable, micro USB",
        type="ACCESSORIES",
        included=False,
        net_list_price=84.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="DA3",
        description="Parking Assistance Package",
        type="PACKAGES",
        included=False,
        net_list_price=1100.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="DA2",
        description="Driver Assistance Package",
        type="PACKAGES",
        included=False,
        net_list_price=1700.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="640",
        description="LED Intelligent Light System",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=750.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="D07",
        description="Wheel locking bolts",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=160.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="D49",
        description="First-aid kit",
        type="STAND_ALONE_OPTIONS",
        included=False,
        net_list_price=35.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040027007519",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=18.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040027007756",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=25.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040027009040",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=19.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040027009130",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=19.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A00040027009283",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=23.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0008211856",
        description="Adapter, for trailer",
        type="ACCESSORIES",
        included=False,
        net_list_price=41.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0009701802",
        description="DUO plus child seat, with ISOFIX, USA",
        type="ACCESSORIES",
        included=False,
        net_list_price=656.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0009702202",
        description="Replacement cover for KIDFIX",
        type="ACCESSORIES",
        included=False,
        net_list_price=125.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0019901607",
        description="Rim locks, M14 x 1.5 x 27",
        type="ACCESSORIES",
        included=False,
        net_list_price=104.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A17140001255337",
        description="Hub cap, star with laurel wreath, classic design",
        type="ACCESSORIES",
        included=False,
        net_list_price=17.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A17140001257P70",
        description="Hub cap, star with laurel wreath, classic design",
        type="ACCESSORIES",
        included=False,
        net_list_price=22.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A17140001259040",
        description="Hub cap, star with laurel wreath, classic design",
        type="ACCESSORIES",
        included=False,
        net_list_price=23.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2054000100",
        description="Compact spare wheel",
        type="ACCESSORIES",
        included=False,
        net_list_price=416.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540102007756",
        description="5-twin-spoke wheel, 43.2 cm (17 inch)",
        type="ACCESSORIES",
        included=False,
        net_list_price=600.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540102007X21",
        description="5-twin-spoke wheel, 43.2 cm (17 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=647.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540102007X23",
        description="5-twin-spoke wheel, 43.2 cm (17 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540103007756",
        description="Multi-spoke wheel, 43.2 cm (17 inch)",
        type="ACCESSORIES",
        included=False,
        net_list_price=700.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540108007X44",
        description="5-spoke wheel, 43.2 cm (17 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=720.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540109007X36",
        description="Multi-spoke wheel, 45.7 cm (18 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=740.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540110007X36",
        description="Multi-spoke wheel, 45.7 cm (18 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=645.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540121007X45",
        description="10-hole wheel, 43.2 cm (17 inch)",
        type="ACCESSORIES",
        included=False,
        net_list_price=725.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540127007X23",
        description="5-twin-spoke wheel, 48.3 cm (19 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=770.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540127007X44",
        description="5-twin-spoke wheel, 48.3 cm (19 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=910.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540128007X23",
        description="5-twin-spoke wheel, 48.3 cm (19 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=800.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540128007X44",
        description="5-twin-spoke wheel, 48.3 cm (19 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=925.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540128027X21",
        description="5-twin-spoke wheel, 45.7 cm (18 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=820.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540129007X21",
        description="10-spoke wheel, 48.3 cm (19 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=920.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540129007X72",
        description="10-spoke wheel, 48.3 cm (19 inch), high-sheen rim edge",
        type="ACCESSORIES",
        included=False,
        net_list_price=780.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540129027X21",
        description="5-twin-spoke wheel, 45.7 cm (18 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=820.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540130007X21",
        description="10-spoke wheel, 48.3 cm (19 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=860.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540130007X72",
        description="10-spoke wheel, 48.3 cm (19 inch), high-sheen rim edge",
        type="ACCESSORIES",
        included=False,
        net_list_price=770.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540131027X21",
        description="6-spoke wheel, 48.3 cm (19 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=860.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540143007X45",
        description="5-twin-spoke wheel, 43.2 cm (17 inch)",
        type="ACCESSORIES",
        included=False,
        net_list_price=570.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540167007X21",
        description="5-twin-spoke wheel, 48.3 cm (19 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=770.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540168007X21",
        description="5-twin-spoke wheel, 48.3 cm (19 inch), high-sheen",
        type="ACCESSORIES",
        included=False,
        net_list_price=795.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A22040001257258",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=35.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A22040001257756",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=25.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A22040001259283",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=36.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A22040001259771",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=22.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A22240022009040",
        description="Hub cap, star with laurel wreath",
        type="ACCESSORIES",
        included=False,
        net_list_price=22.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B66470200",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=23.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B66470202",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=22.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B66470203",
        description="Hub cap, recessed star",
        type="ACCESSORIES",
        included=False,
        net_list_price=22.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B66470206",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=21.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B66470207",
        description="Hub cap, raised star",
        type="ACCESSORIES",
        included=False,
        net_list_price=22.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B66472002",
        description="Valve cap, set of 4",
        type="ACCESSORIES",
        included=False,
        net_list_price=22.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B66588140",
        description="Tyre pressure gauge",
        type="ACCESSORIES",
        included=False,
        net_list_price=38.5,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20540107007X35",
        description="5-spoke wheel, 45.7 cm (18 inch)",
        type="ACCESSORIES",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0005834300",
        description="Fluorescent jacket, compact, USA/CAN",
        type="ACCESSORIES",
        included=False,
        net_list_price=9.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0009062909",
        description="Micro-SD card, 32 GB",
        type="ACCESSORIES",
        included=False,
        net_list_price=66.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0009822921",
        description="Charger with trickle charge function, 5 A, for lead-acid and lithium batteries, USA",
        type="ACCESSORIES",
        included=False,
        net_list_price=139.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A0009865500",
        description="Microfibre cloth",
        type="ACCESSORIES",
        included=False,
        net_list_price=5.25,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2055800100",
        description="Vehicle tool kit",
        type="ACCESSORIES",
        included=False,
        net_list_price=128.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20568010489G32",
        description="Rep floor mats CLASSIC, driver’s/co-driver’s mat, 2-piece",
        type="ACCESSORIES",
        included=False,
        net_list_price=108.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20568012489G32",
        description="Rep floor mats CLASSIC, driver’s/co-driver’s mat, 2-piece",
        type="ACCESSORIES",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20568022488S85",
        description="All-season floor mats CLASSIC, driver’s/co-driver’s mat, 2-piece",
        type="ACCESSORIES",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A20568022489G33",
        description="All-season floor mats CLASSIC, driver’s/co-driver’s mat, 2-piece",
        type="ACCESSORIES",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="A2536932000",
        description="Concertina load sill protector",
        type="ACCESSORIES",
        included=False,
        net_list_price=61.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
    LineItemOptionCode(
        code="B67550042",
        description="Snow chain, RUD-matic DISC",
        type="ACCESSORIES",
        included=False,
        net_list_price=0.0,
        gross_list_price=0.0,
        predicted_category="",
    ),
]
